---
title: "Application 1"
author: "Kossi"
date: "11/01/2020"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

<br>

# Extraction des principaux taux de change sur MSN

Dans cette partie, nous allons mettre en pratique tout ce que nous avons déjà  appris dans ce cours. En mobilisant les différents points déjà  abordés, nous irons récupérer des données financières en temps réel sur **MSN**.

<br><br>
<div class="alert alert-warning">
     MSN est un portail de services web détenu par Microsoft.
</div>

Ouvrons la page des taux de change **MSN** avec la librairie **requests** :
```{python}
import requests
from bs4 import BeautifulSoup
msn = requests.get("https://www.msn.com/en-us/money/markets/currencies")
print( "code d'état :", msn.status_code)
soup = BeautifulSoup(msn.text)
```

**Q1** Quelle est la plus petite classe qui englobe notre table d'intérêt ? Appelons  cette classe `currency_class`. Modifiez le code ci-dessous pour ne sélectionner que la classe `currency_class`.

```{python, echo = FALSE}
currency_class = "mjrcurrncsitem"
```

```{python}
# N'oubliez pas de définir currency_class
cur = soup.find( class_ =  currency_class) # Retenez cette syntaxe, elle permet d'extraire une classe quelconque
if cur and len(cur) :
  print("Bravo: il semblerait que j'ai trouvé la classe!")
else:
  print("Je n'ai toujours pas trouvé la classe mère")
```

<br>
<div class="alert alert-warning">
     Pour trouver la classe `currency_class`, vous pouvez vous servir de votre navigateur Web en faisant 'CTRL + I' ou 'Click droit + Inspecter cette page'
</div>
<br>


**Q2** Quelle est la classe qui représente l'en-tête de la table ? Notons-la `thead_class`. Alors l'en-tête s'extrait de la façon suivante :

```{python, echo = FALSE}
thead_class = "tblheaderrow"
```

```{python}
# N'oubliez pas de définir thead_class
header = cur.find(class_ = thead_class)
headers = header.find_all(class_ = "mctblheading") # Avez-vous pu retrouver la classe `mctblheading`  de vous mêmes ?
header_values = []
for header in headers :
    header_values.append(header.find("p").attrs["title"])
print(header_values)
```
<br>

**Q3** Quelle est la classe qui englobe toutes les lignes de la table ? Elle sera notée `trows_class`. Pouvez-vous identifier la classe qui caractérise une ligne dans la table ? Notons cette classe `trow_class'.
```{python, echo = FALSE}
trows_class = "mjcurrncs-data"
trow_class = "mcrow"
```

```{python}
rows_container = cur.find(class_ = trows_class)
rows = rows_container.find_all(class_ = "mcrow")
row = rows[0]
print(row)
```
<br>

**Q4**  En vous servant de la variable **row** définie dans la question précédente, trouvez les classes qui représentent :

* La monnaie de base
* La paire de monnaies de change
* Le cours/prix de change
* La variation absolue du cours
* La variation en pourcentage du cours

**Extraire chacun des champs sus-mentionnés**.

Quelle est la classe commune au maximum et minimum annuel des cours ? Pouvez-vous dire **l'attribut HTML** qui différencie le cours minimum du cours maximum ? Extraire les 2 cours. Extrayez les 2 cours.
<br>

**Q5** En vous servant de la question **Q4**, écrire une fonction qui prend en entrée une ligne de la table et  extrait ses champs. Utilisez cette fonction pour extraire toutes les lignes de la table dans une liste de dictionnaire.
<br>

**Q6** En utilisant la librairie **pandas**, convertissez la liste de la question **5** en un **dataframe** (n'hésitze pas à vous inspirer de l'en-tête de la table pour définir le nom de vos colonnes).

Vous devriez obtenir une table de la forme :
```{python, echo = FALSE}
import pandas as pd
def get_row(row):
    currency = row.find(class_ = "cntrycol").p.attrs["title"]
    pairs = row.find(class_ = "cnvrsncol").p.attrs["title"]
    price = row.find(class_ =  "pricecol").p.text
    change = row.find(class_ =  "chngcol").p.text
    pchange = row.find(class_ =  "chpcol").p.text
    
    rng52wkcol2 = row.find_all(class_ =  "rng52wkcol")
    assert len(rng52wkcol2) == 2
    #.find(attrs = {"aria-label": lambda x: x and "high" in x.lower()}).text
    rng_vals = {}
    for rng in rng52wkcol2:
        p = rng.find("p")
        if "high" in p.attrs["aria-label"].lower():
            rng_vals["rng52wkcol_high"] = p.text
        else:
            rng_vals["rng52wkcol_low"] = p.text
            
    res = dict(currency = currency,pairs = pairs, price = price, change=change, pchange = pchange)
    res.update(rng_vals)
    return res
    
rows = cur.find(class_ = "mjcurrncs-data").find_all(class_ = "mcrow")
df = pd.DataFrame([get_row(row) for row in rows])
df.head()
```

<br>

**Q7** Au vu de nos données, quel est le taux de  conversion le plus élevé ? Pouvez-vous visualiser ces taux à  l'aide d'un diagramme en bâtons (barplot) ?
<br>

**Q8** Reconstruire la table pandas de la question **7** en n'utilisant cette fois que des **sélecteurs CSS**.
<br>

**BRAVO, vous avez réussi à scraper votre premier page Web !**.
