---
title: "Site dynamic"
author: "Kossi"
date: "11/01/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Pages dynamiques, mais comment ça ?

Je vous disais dans le premier chapitre de ce cours que la grande différence entre les pages Web et un document pdf est la dynamicité des premiers. Avec du JavaScript, le rendu d'une page web peut changer à tout moment en fonction des interactions avec l'utilisateur. Par exemple, sur certains sites, vous n'avez qu'un contenu minimal si vous n'êtes pas authentifié. Et même si vous êtes authentifié, selon les boutons que vous cliquez et selon vos déplacements de souris, le rendu de la page peut changer. Tous ses aspects rendent le scraping beaucoup  plus compliqués. Pourquoi ? Dans l'application de tout à l'heure nous avons téléchargé le code source de la page et nous avons extraits les données qui nous intéressent. Eh bien, ce schéma de travail n'est plus utilisable du moment où le code source ne contient que quelques scripts (sans données) qui vont se charger d'aller chercher les données et les afficher selon nos interactions avec la page. Pour obliger le serveur à vous montrer les données, il faut exécuter le javascript de la page et pour ce faire il faut se doter d'un outil bien adapté. Peut importe l'outil, la nécessité d'activer du javascript sur une page ralenti le processus de **scraping**. Mais pour des applications de taille raisonnable, cette perte de rapidité ne constituera pas un vrai frein au projet de récupération de données. Autrement, il va falloir identifier soi même et n'activer que les javascripts les plus 'intéressants'. Il est aussi possible de régarder directement les requêtes envoyées par le navigateur et reconstituer soi même la procédure complète requise pour récupérer la donnée de la page d'intérêt.


# Authentification
Les sites Web mettent généralement en place des politiques d'authentification de leurs utilisateurs. Plusieurs protcoles d'authentification sont accessbiles sur Internet : 

## Basic Authentication
La plupart des sites Web acceptent l'authentification **Basic HTTP** qui est la méthode d'authentification la plus simple sur une page Web. **Basic HTTP** est entièrement géré par la libraire **requests** elle même.

```{python}

```



# Cookies
**Un cookie** est un petit fichier texte contentant des paires de **clé-valuer**. Ces **clés-valeurs** permettent aux sites de fournier des services personnalisés. En pyhton il est possible d'ajouter des cookies à sa requête HTTP.

# Proxy

# Actions/évènements javascripts

# Formulaire
Sur le net, les sites récupèrent souvent les données de leurs utilisateurs grâce aux formulaires. Le conetenu de la page peuvent changer seon les informations renseignées dans le formulaire. Et des fois la page peut requérir ces données avant de vous fournir ses services. Il est donc important de savoir comment remplir ces formulaires de façon autimatisée.




